apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: infin8-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infin8-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
