apiVersion: v1
kind: Secret
metadata:
  name: infin8-secrets
type: Opaque
data:
  # Base64 encoded values
  # root -> cm9vdA==
  # dummy ->ZHVtbXk= 
  # Infin8 -> SW5maW44
  mysql-root-password: cm9vdA==
  mysql-password: cm9vdA==
  mysql-user: cm9vdA==
  mysql-db: SW5maW44
  email-password: ZHVtbXk= 
